import { Phrase } from '../shared/phrase.model'

export const PHRASE: Phrase[] = [
  { phraseUS: `I like to learn`, phrasePT: `Eu gosto de aprender` },
  { phraseUS: `I like to eat`, phrasePT: `Eu gosto de comer` },
  { phraseUS: `What is your name?`, phrasePT: `Qual é o seu nome?` },
  { phraseUS: `My name is Jake.`, phrasePT: `Meu nome é Jake.` },
  /* { phraseUS: `Hello. How are you?`, phrasePT: `Oi. Como está você?` },
   { phraseUS: `I am fine, and you?`, phrasePT: `Eu estou bem, e você?` },
   { phraseUS: `Nice to meet you!`, phrasePT: `Prazer em te conhecer!` },
   { phraseUS: `I am thirsty`, phrasePT: `Estou com sede` },
   { phraseUS: `I am cold`, phrasePT: `Estou com frio` },
   { phraseUS: `How old are you?`, phrasePT: `Qual a sua idade?` },
   { phraseUS: `Please!`, phrasePT: `Por favor!` },
   { phraseUS: `I'm sorry`, phrasePT: `Me desculpa` },
   { phraseUS: `Have a nice weekend!`, phrasePT: `Tenha um bom final de semana` },
   { phraseUS: `Where do you live?`, phrasePT: `Onde você mora?` },
   { phraseUS: `How much?`, phrasePT: `Quanto é?` },
   { phraseUS: `What do you do?`, phrasePT: `O que você faz?` },
   { phraseUS: `I am a lawyer`, phrasePT: `Eu sou advogado` },
     { phraseUS: `What do you do for living?`, phrasePT: `Qual é a sua profissão?` },
    { phraseUS: `Do you have any children?`, phrasePT: `Você tem filhos?` },
    { phraseUS: `Do you have any brothers or sisters?`, phrasePT: `Você tem irmãos?` },
    { phraseUS: `Would you like some juice?`, phrasePT: `Você aceita suco?` },
    { phraseUS: `Where is the restroom?`, phrasePT: `Onde é o banheiro?` },
    { phraseUS: `What do you think about Brazil?`, phrasePT: `O que você acha do Brasil?` },
    { phraseUS: `I agree with you.`, phrasePT: `Eu concordo com você.` },
    { phraseUS: `When is your birthday`, phrasePT: `Quando é o seu aniversário?` },
    { phraseUS: `Is there a hotel near here?`, phrasePT: `Tem um hotel aqui perto?` },
    { phraseUS: `Good morning!`, phrasePT: `Bom dia!` },
    { phraseUS: `Good evening!`, phrasePT: `Boa tarde!` },
    { phraseUS: `Sorry, could you repeat, please?`, phrasePT: `Desculpe, você pode repetir, por favor?` },
    { phraseUS: `Could you write it down, please?`, phrasePT: `Você poderia escrever, por favor?` },
    { phraseUS: `I’m in your country for the first time`, phrasePT: ` Estou em seu país pela primeira vez.` },
    { phraseUS: `I’m not feeling very well`, phrasePT: `Eu não estou me sentindo muito bem` },
    { phraseUS: `Can I have the bill/check, please`, phrasePT: `Pode trazer a conta, por favor?` },
    { phraseUS: `I would like a single/double bedroom, please`, phrasePT: `Eu gostaria de um quarto de solteiro/casal, por favor.` },
    { phraseUS: `How much is a room for two people?`, phrasePT: `Quanto custa um quarto para duas pessoas?` },
    { phraseUS: `Is there a restaurant in the hotel?`, phrasePT: `Há um restaurante no hotel?` },
    { phraseUS: `Can I check out of my room later, please?`, phrasePT: `Posso fazer check out mais tarde, por favor?` },
    { phraseUS: `Can I check out of my room later, please?`, phrasePT: `Posso fazer check out mais tarde, por favor?` },
    { phraseUS: `Where can I buy tickets?`, phrasePT: `Onde eu posso comprar as passagens?` },
    { phraseUS: `I would like to buy a ticket to New York, please`, phrasePT: `Eu gostaria de comprar uma passagem para Nova York, por favor.` },
    { phraseUS: `How can I get to the main train station please?`, phrasePT: `Como eu chego à estação central de trem, por favor?` }, */
]
